name: Go CI

on:
  push:
    branches: [dev]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v4

      # Setup Go
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # Install protoc (if you need the compiler)
      - name: Install protoc
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler

      # Install Go proto tools
      - name: Install Go proto packages
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      # Build using make
      - name: Build
        run: make build
S